# Generated by Django 3.0.4 on 2020-07-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrovalleyapp', '0003_post_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='product',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
