# Generated by Django 3.0.4 on 2020-07-15 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retrovalleyapp', '0006_auto_20200714_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
