# Generated by Django 3.0.4 on 2020-07-15 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retrovalleyapp', '0007_auto_20200715_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retrovalleyapp.Category'),
        ),
    ]
